var frameTitle = [{
    //link: 'https://i.pinimg.com/originals/68/83/58/6883588c46d58007614c57109a9a5996.jpg',
    link: '../images/Boeing.gif',
    type: 'logo',
  },
  {
    title: 'Power Distribution - Renton site',
    type: 'label',
  },
  {
    title: 'Unit Sub',
    type: 'label',
  },
  {
    title: 'PDS',
    type: 'label',
  },

  {
    title: 'Alt/3rd',
    type: 'label',
  },
  {
    title: 'Tied',
    type: 'label',
  },
  {
    title: 'Substation 1',
    type: 'label',
  },
  {
    title: 'Substation 2',
    type: 'label',
  },
];

var data = [{
    unit: 'Vault 01',
    type: 'vault',
    table: 'main',
    primary: '1B13B',
    secondary: '2B13B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 02',
    type: 'vault',
    table: 'main',
    primary: '2B13B',
    secondary: '1B13B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 14A',
    type: 'vault',
    table: 'main',
    primary: '2A7B',
    secondary: '1A5A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 14B',
    type: 'vault',
    table: 'main',
    primary: '1A5B',
    secondary: '2B12A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 21',
    type: 'vault',
    table: 'main',
    primary: '1B12B',
    secondary: '2B14B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 22',
    type: 'vault',
    table: 'main',
    primary: '2B14B',
    secondary: '1B12B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 23A',
    type: 'vault',
    table: 'main',
    primary: '1B14B',
    secondary: '2B12A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 23B',
    type: 'vault',
    table: 'main',
    primary: '2B14A',
    secondary: '1A7B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 24A',
    type: 'vault',
    table: 'main',
    primary: '1B14B',
    secondary: '2A8A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 24B',
    type: 'vault',
    table: 'main',
    primary: '2A8A',
    secondary: '1A7B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 25A',
    type: 'vault',
    table: 'main',
    primary: '2A8A',
    secondary: '1A7B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 25B',
    type: 'vault',
    table: 'main',
    primary: '1B14B',
    secondary: '2A8A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 26A',
    type: 'vault',
    table: 'main',
    primary: '1B14B',
    secondary: '2A8A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 26B',
    type: 'vault',
    table: 'main',
    primary: '2A8A',
    secondary: '1A7B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 27A',
    type: 'vault',
    table: 'main',
    primary: '2B14A',
    secondary: '1B14B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 27B',
    type: 'vault',
    table: 'main',
    primary: '1A7B',
    secondary: '2B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 28',
    type: 'vault',
    table: 'main',
    primary: '1A7B',
    secondary: '2B14A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 29',
    type: 'vault',
    table: 'main',
    primary: '1B13B',
    secondary: '2B13B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 30A',
    type: 'vault',
    table: 'main',
    primary: '2B13B',
    secondary: '1B13B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 30B',
    type: 'vault',
    table: 'main',
    primary: '1B13B',
    secondary: '2B11A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 37',
    type: 'vault',
    table: 'main',
    primary: '2A5B',
    secondary: '1B11B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 41',
    type: 'vault',
    table: 'main',
    primary: '1B11B',
    secondary: '2A5B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 43A',
    type: 'vault',
    table: 'main',
    primary: '2A6B',
    secondary: '1B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 43B',
    type: 'vault',
    table: 'main',
    primary: '1B14A',
    secondary: '2B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 45A',
    type: 'vault',
    table: 'main',
    primary: '1A6B',
    secondary: '2B12A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 45B',
    type: 'vault',
    table: 'main',
    primary: '2B12A',
    secondary: '1A5B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 46',
    type: 'vault',
    table: 'main',
    primary: '2B11A',
    secondary: '1B12A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 48',
    type: 'vault',
    table: 'main',
    primary: '2B12A',
    secondary: '2B11A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 49A',
    type: 'vault',
    table: 'main',
    primary: '2A7B',
    secondary: '1A5B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 49B',
    type: 'vault',
    table: 'main',
    primary: '1A5B',
    secondary: '2B12A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 50A',
    type: 'vault',
    table: 'main',
    primary: '1A5B',
    secondary: '2A7B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 50B',
    type: 'vault',
    table: 'main',
    primary: '2A7B',
    secondary: '1A5B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 51A',
    type: 'vault',
    table: 'main',
    primary: '1A6A',
    secondary: '2A7A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 51B',
    type: 'vault',
    table: 'main',
    primary: '2A7A',
    secondary: '1A6A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 52A',
    type: 'vault',
    table: 'main',
    primary: '1A5A',
    secondary: '2A5A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 52B',
    type: 'vault',
    table: 'main',
    primary: '2A5B',
    secondary: '1A8A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 53A',
    type: 'vault',
    table: 'main',
    primary: '2A7A',
    secondary: '1A6A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 53B',
    type: 'vault',
    table: 'main',
    primary: '2A7A',
    secondary: '1A6A',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 54A',
    type: 'vault',
    table: 'main',
    primary: '1B12B',
    secondary: '2B14B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 54B',
    type: 'vault',
    table: 'main',
    primary: '2B14B',
    secondary: '1B12B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 55A',
    type: 'vault',
    table: 'main',
    primary: '2A6B',
    secondary: '1B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 55B',
    type: 'vault',
    table: 'main',
    primary: '1B14A',
    secondary: '2B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 56A',
    type: 'vault',
    table: 'main',
    primary: '2A6B',
    secondary: '1B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 56B',
    type: 'vault',
    table: 'main',
    primary: '1B14A',
    secondary: '2B14A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 6A',
    type: 'vault',
    table: 'main',
    primary: '1A7A',
    secondary: '2B12B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 6B',
    type: 'vault',
    table: 'main',
    primary: '2B12B',
    secondary: '1A6B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 7A',
    type: 'vault',
    table: 'main',
    primary: '1A7B',
    secondary: '2B12B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 7B',
    type: 'vault',
    table: 'main',
    primary: '2B12B',
    secondary: '1A6B',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 8A',
    type: 'vault',
    table: 'main',
    primary: '1A5A',
    secondary: '2A5A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault 8B',
    type: 'vault',
    table: 'main',
    primary: '2A5A',
    secondary: '1A8A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault AC5A',
    type: 'vault',
    table: 'main',
    primary: '2A5B',
    secondary: '1B11B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault AC5B',
    type: 'vault',
    table: 'main',
    primary: 'n/a',
    secondary: '2A5B',
    tied: 'false',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault AC8A',
    type: 'vault',
    table: 'main',
    primary: '1A8A',
    secondary: '2A6A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: 'Vault AC8B',
    type: 'vault',
    table: 'main',
    primary: '2A6A',
    secondary: '1A5A',
    tied: 'true',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A5A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A5B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A6A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A6B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A7A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A7B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A8A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1A8B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B11A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B11B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B12A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B12B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B13A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B13B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B14A',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '1B14B',
    type: 'feed',
    table: 'sub1',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A5A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A5B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A6A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A6B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A7A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A7B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A8A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2A8B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B11A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B11B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B12A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B12B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B13A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'deactivated',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B13B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B14A',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  },
  {
    unit: '2B14B',
    type: 'feed',
    table: 'sub2',
    latched: 'false',
    activityStatus: 'active',
    building: '',
    timestamp: '20180713',
    userid: 'dan.fujimura',
  }
];
